spring:
  profiles:
    active:
    - dev

---
spirng:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-atguigu-dev

---
spirng:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-atguigu-test
    
# 保存格式为UTF-8 格式